# Generated by Django 4.1.5 on 2023-01-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_musicuploader_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='myapp/static')),
                ('video', models.FileField(upload_to='myapp/static')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='musicuploader',
            options={'ordering': ('-id',)},
        ),
    ]
