# Generated by Django 4.1.5 on 2023-01-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_movie_alter_musicuploader_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created',
        ),
    ]
