# Generated by Django 4.1.5 on 2023-01-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_movie_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='movie_image',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='movie_title',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='video',
            new_name='movie_video',
        ),
    ]
