# Generated by Django 4.1.5 on 2023-01-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_movie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-id',)},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_video',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_title',
            new_name='title',
        ),
    ]
