# Generated by Django 4.1.5 on 2023-01-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_movie_options_rename_movie_image_movie_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
