# Generated by Django 4.1.5 on 2023-01-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='imageUrl',
        ),
    ]
