# Generated by Django 4.1.5 on 2023-01-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_music_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.CharField(max_length=255),
        ),
    ]
