# Generated by Django 4.1.5 on 2023-01-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_music_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='musicPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='myapp/static')),
                ('file', models.FileField(upload_to='myapp/static')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
